name: Deploy AI_Erhu Folder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Show files in audio/AI_Erhu
        run: |
          echo "Listing contents of audio/AI_Erhu:"
          ls -l ./audio/AI_Erhu

      - name: Deploy AI_Erhu audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}
          publish_dir: ./audio/AI_Erhu
          destination_dir: audio/AI_Erhu
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
