name: Deploy Full Demo Site

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy full site to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true
