name: Deploy Violin Folder

on:
  workflow_dispatch:  # 👉 手動觸發用

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Violin audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./audio/Violin
          destination_dir: audio/Violin
