name: Deploy AI_Erhu Folder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy AI_Erhu audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}
          publish_dir: ./audio/AI_Erhu
          destination_dir: audio/AI_Erhu
          publish_branch: gh-pages
          force_orphan: false
