name: Deploy Piano Folder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Show files in audio/Piano
        run: |
          echo "Listing contents of audio/Piano:"
          ls -l ./audio/Piano

      - name: Deploy Piano audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}
          publish_dir: ./audio/Piano
          destination_dir: audio/Piano
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
