name: Deploy Violin Folder

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Show files in audio/Violin
        run: |
          echo "Listing contents of audio/Violin:"
          ls -l ./audio/Violin

      - name: Deploy Violin audio to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TIMBRE }}
          publish_dir: ./audio/Violin
          destination_dir: audio/Violin
          publish_branch: gh-pages
          keep_files: true
          force_orphan: false
